In [4]:
import pandas as pd 
df = pd.read_csv('products_catalog.csv')
df.head(5)

,product_id,product_name,brand,category,price,currency,stock_quantity,rating,sku,description
0,FA-2005,Women's Silk Blend Saree,FabIndia,Fashion,5999,INR,373,4.3,SKU-FA-2005,Luxurious silk blend traditional saree with bo...
1,HK-3021,Microfiber Cleaning Cloth Pack,Scotch-Brite,Home & Kitchen,399,INR,418,4.3,SKU-HK-3021,Super absorbent microfiber cloths for cleaning
2,HK-3004,Digital Air Fryer 4.2L,Havells,Home & Kitchen,6990,INR,250,5.0,SKU-HK-3004,Oil free digital air fryer for healthy snacks
3,HK-3010,Induction Cooktop 2000W,Prestige,Home & Kitchen,2799,INR,357,4.2,SKU-HK-3010,Efficient induction cooktop with touch controls
4,FA-2006,Men's Checked Formal Shirt,Van Heusen,Fashion,1999,INR,162,3.6,SKU-FA-2006,Premium checked formal shirt for office wear

In [11]:
## Handling missing values
# finding missing values 
df.isnull().any(axis=1)
df.isnull().sum()
## filling missing values 
df.fillna(0)
df['Sales_fillNA'] = df['price'].fillna(df['price'].mean())
df

,product_id,product_name,brand,category,price,currency,stock_quantity,rating,sku,description,Sales_fillNA
0,FA-2005,Women's Silk Blend Saree,FabIndia,Fashion,5999,INR,373,4.3,SKU-FA-2005,Luxurious silk blend traditional saree with bo...,5999
1,HK-3021,Microfiber Cleaning Cloth Pack,Scotch-Brite,Home & Kitchen,399,INR,418,4.3,SKU-HK-3021,Super absorbent microfiber cloths for cleaning,399
2,HK-3004,Digital Air Fryer 4.2L,Havells,Home & Kitchen,6990,INR,250,5.0,SKU-HK-3004,Oil free digital air fryer for healthy snacks,6990
3,HK-3010,Induction Cooktop 2000W,Prestige,Home & Kitchen,2799,INR,357,4.2,SKU-HK-3010,Efficient induction cooktop with touch controls,2799
4,FA-2006,Men's Checked Formal Shirt,Van Heusen,Fashion,1999,INR,162,3.6,SKU-FA-2006,Premium checked formal shirt for office wear,1999
...,...,...,...,...,...,...,...,...,...,...,...
115,HK-3014,King Size Cotton Bedsheet,Bombay Dyeing,Home & Kitchen,1999,INR,64,4.8,SKU-HK-3014,Soft breathable cotton bedsheet with pillow co...,1999
116,EL-1021,Bajaj Majesty Steam Iron,Bajaj,Electronics,1299,INR,230,4.0,SKU-EL-1021,Quick heating steam iron with non-stick soleplate,1299
117,EL-1010,OnePlus Nord Buds 2,OnePlus,Electronics,2999,INR,198,4.8,SKU-EL-1010,True wireless earbuds with fast charging,2999
118,EL-1004,Apple AirPods Pro 2nd Gen,Apple,Electronics,26900,INR,451,4.6,SKU-EL-1004,Active noise cancellation true wireless earbuds,26900
119,BE-5008,Sunscreen SPF 50 Gel 50g,Biotique,Beauty & Personal Care,499,INR,440,4.9,SKU-BE-5008,Lightweight sunscreen protection against UV rays,499