In [ ]:
# Pandas 
# It is widely used in data-analysis and data-cleaning 
# Provides primary two data structures:Series and dataframe 
# Series is one dimensional array like object 
# DataFrame is two dimensional ,size-mutable and potentially heterogenous 
# tabular data structure with labeled axis(row and columns)
import pandas as pd 
data = [1,2,3,4,5]
series = pd.Series(data)
series
# 0 1 2 3 4 5 is basically indexes

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# Series from dictionary elements
data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [3]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index)

a    10
b    20
c    30
dtype: int64

In [8]:
#DataFrame 
# Create dataframe from dictionary of list 
data = {
    'name':['Divyanshu','Tanmay','Vansh','Divy','Divyesh'],
    'age':[25,24,24,27,26],
    'city':['Bangalore','New York','Chicago','Florida','Las Vegas']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

        name  age       city
0  Divyanshu   25  Bangalore
1     Tanmay   24   New York
2      Vansh   24    Chicago
3       Divy   27    Florida
4    Divyesh   26  Las Vegas
<class 'pandas.DataFrame'>

In [9]:
# Create dataframe from list of dictionaries
data = [
    {'Name':'Divyanshu','age':26,'city':'Jaipur'},
    {'Name':'Divy','age':27,'city':'Dubai'},
    {'Name':'Darshan','age':28,'city':'Bangalore'}
]
df = pd.DataFrame(data)
df

        Name  age       city
0  Divyanshu   26     Jaipur
1       Divy   27      Dubai
2    Darshan   28  Bangalore

In [12]:
df = pd.read_csv('products_catalog.csv')
#first 5 records
print(df.head())
#last 5 records 
print(df.tail())
df['product_name']

  product_id                    product_name         brand        category  \
0    FA-2005        Women's Silk Blend Saree      FabIndia         Fashion
1    HK-3021  Microfiber Cleaning Cloth Pack  Scotch-Brite  Home & Kitchen
2    HK-3004          Digital Air Fryer 4.2L       Havells  Home & Kitchen
3    HK-3010         Induction Cooktop 2000W      Prestige  Home & Kitchen
4    FA-2006      Men's Checked Formal Shirt    Van Heusen         Fashion

   price currency  stock_quantity  rating          sku  \
0   5999      INR             373     4.3  SKU-FA-2005
1    399      INR             418     4.3  SKU-HK-3021
2   6990      INR             250     5.0  SKU-HK-3004
3   2799      INR             357     4.2  SKU-HK-3010
4   1999      INR             162     3.6  SKU-FA-2006

                                         description
0  Luxurious silk blend traditional saree with bo...
1     Super absorbent microfiber cloths for cleaning
2      Oil free digital air fryer for healthy snacks
3    Efficient induction cooktop with touch controls
4       Premium checked formal shirt for office wear
    product_id               product_name          brand  \
115    HK-3014  King Size Cotton Bedsheet  Bombay Dyeing
116    EL-1021   Bajaj Majesty Steam Iron          Bajaj
117    EL-1010        OnePlus Nord Buds 2        OnePlus
118    EL-1004  Apple AirPods Pro 2nd Gen          Apple
119    BE-5008   Sunscreen SPF 50 Gel 50g       Biotique

                   category  price currency  stock_quantity  rating  \
115          Home & Kitchen   1999      INR              64     4.8
116             Electronics   1299      INR             230     4.0
117             Electronics   2999      INR             198     4.8
118             Electronics  26900      INR             451     4.6
119  Beauty & Personal Care    499      INR             440     4.9

             sku                                        description
115  SKU-HK-3014  Soft breathable cotton bedsheet with pillow co...
116  SKU-EL-1021  Quick heating steam iron with non-stick soleplate
117  SKU-EL-1010           True wireless earbuds with fast charging
118  SKU-EL-1004    Active noise cancellation true wireless earbuds
119  SKU-BE-5008   Lightweight sunscreen protection against UV rays

0            Women's Silk Blend Saree
1      Microfiber Cleaning Cloth Pack
2              Digital Air Fryer 4.2L
3             Induction Cooktop 2000W
4          Men's Checked Formal Shirt
                    ...
115         King Size Cotton Bedsheet
116          Bajaj Majesty Steam Iron
117               OnePlus Nord Buds 2
118         Apple AirPods Pro 2nd Gen
119          Sunscreen SPF 50 Gel 50g
Name: product_name, Length: 120, dtype: str

In [ ]:
# 0th row 
df.loc[2]

product_id                                                  FA-2005
product_name                               Women's Silk Blend Saree
brand                                                      FabIndia
category                                                    Fashion
price                                                          5999
currency                                                        INR
stock_quantity                                                  373
rating                                                          4.3
sku                                                     SKU-FA-2005
description       Luxurious silk blend traditional saree with bo...
Name: 0, dtype: object

In [19]:
df.iloc[2]

product_id                                              HK-3004
product_name                             Digital Air Fryer 4.2L
brand                                                   Havells
category                                         Home & Kitchen
price                                                      6990
currency                                                    INR
stock_quantity                                              250
rating                                                      5.0
sku                                                 SKU-HK-3004
description       Oil free digital air fryer for healthy snacks
Name: 2, dtype: object

In [28]:
# Accessing specified element
df.at[1,'brand']
# Accessing element column-wise
df.iat[2,2]

# Remove a column temporarily and do not save the state of dataframe
df.drop('category',axis=1)
df.drop('category',axis=1,inplace=True)
df

,product_id,product_name,brand,price,currency,stock_quantity,rating,sku,description
0,FA-2005,Women's Silk Blend Saree,FabIndia,5999,INR,373,4.3,SKU-FA-2005,Luxurious silk blend traditional saree with bo...
1,HK-3021,Microfiber Cleaning Cloth Pack,Scotch-Brite,399,INR,418,4.3,SKU-HK-3021,Super absorbent microfiber cloths for cleaning
2,HK-3004,Digital Air Fryer 4.2L,Havells,6990,INR,250,5.0,SKU-HK-3004,Oil free digital air fryer for healthy snacks
3,HK-3010,Induction Cooktop 2000W,Prestige,2799,INR,357,4.2,SKU-HK-3010,Efficient induction cooktop with touch controls
4,FA-2006,Men's Checked Formal Shirt,Van Heusen,1999,INR,162,3.6,SKU-FA-2006,Premium checked formal shirt for office wear
...,...,...,...,...,...,...,...,...,...
115,HK-3014,King Size Cotton Bedsheet,Bombay Dyeing,1999,INR,64,4.8,SKU-HK-3014,Soft breathable cotton bedsheet with pillow co...
116,EL-1021,Bajaj Majesty Steam Iron,Bajaj,1299,INR,230,4.0,SKU-EL-1021,Quick heating steam iron with non-stick soleplate
117,EL-1010,OnePlus Nord Buds 2,OnePlus,2999,INR,198,4.8,SKU-EL-1010,True wireless earbuds with fast charging
118,EL-1004,Apple AirPods Pro 2nd Gen,Apple,26900,INR,451,4.6,SKU-EL-1004,Active noise cancellation true wireless earbuds
119,BE-5008,Sunscreen SPF 50 Gel 50g,Biotique,499,INR,440,4.9,SKU-BE-5008,Lightweight sunscreen protection against UV rays

In [30]:
df['stock_quantity'] = df['stock_quantity']+1